### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/rails-video-review-authentication#1]
_Suggested Summary_
- In this video lecture, we discuss _validation_ and _authentication_ in a Rails app, using the TodoMVC example that we have been building throughout this section of the course. We also go over _cookies / session_ and talk about how they allow us to carry information between requests in an otherwise stateless protocol (HTTP)

_Suggested Objectives_
- Explain the difference between _authentication_ and _authorization_
- Remember that we like to have _skinny controllers_, which we can achieve by placing logic in the models
- Use validations on models in order to keep the database clean and your controllers skinny
- Understand what a _validation event_ is in an object’s lifecycle and when it occurs
- Access the errors placed in an object’s error attribute
- Clarify what we mean when we say that HTTP is a _stateless protocol_
- Define a _cookie_ and explain how they allow us to carry over state, from request to request (and why this is important)
- Avoid storing data directly in a user’s cookies and, instead, place it in the _session_
- Define an _inheritance point_ and explain why we place helper methods that we want all controllers to have access to inside the _ApplicationController_
- Use the _helper_method_ macro to make controller methods available in their corresponding views
- Always avoid storing plain text passwords in your database; instead use _has_secure_password_, _password_digest_ and _bcrypt_ to set and store a user’s password in a secure way

**Comment by Sdcrouse** [comment]
I like this. It's too bad they closed this issue.
